### ISSUE TITLE
Wemo D1 mini

### ISSUE THREAD

**Issue by amaximus** [Margriko/Paradox-ESPHome#2]
Not an issue, rather a request for help (the discussion section is unfortunately not available).

Thanks for your work on connecting Paradox alarm panels to HomeAssistant.

I'm planning to connect unidirectionally my old Paradox Spectra 1728EX panel to HomeAssistant and your work and repo gave me a hope that it can be done.
I'm planning to connect it via Wemo D1 mini that supports I2C and SPI modes [1]. Looking at your wiring diagram, since your diagram uses only a clock and a data pin I suppose it's I2C. Could you please confirm?
Since I plan to power the Wemo D1 mini from an USB adapter I presume that the Alarm Aux +/- connections are not needed. Neither the voltage regulator. Am I right?

Thanks in advance.

[1] https://escapequotes.net/esp8266-wemos-d1-mini-pins-and-diagram/

**Comment by Margriko** [comment]
Hi!
I am not good at hardware stuff, but I think that it is not SPI or I2C. I fit was then the projects I referenced in description would use libraries for these protocols and we would not need to reinvent the wheel.
About connecting Alarm Aux +/- you are right - if you connect Wemos from USB then no external power is needed.
Some side notes about this project:
- the best way to connect data and clock wires would be by using logic level converters (12v to 3.3v), in the future I am going to try it out myself.
- I really miss the write capability, so that I could arm remotely. If I had more spare time then I would rewrite everything from scratch by using "DSC keybus interface" as an example with the timing and data adjustments from here, as those protocols look rather similar.

**Comment by amaximus** [comment]
Hi,

thanks for your quick reply. One more small clarification:
* for the alarm green/yellow connection, the ground that it should be connected to (after the 15+10 kOhm resistors) is the alarm panel ground or the Wemo D1 mini's ground?

Thanks again!

**Comment by Margriko** [comment]
Sorry for late reply. It should be Wemo D1 mini's ground

**Comment by amaximus** [comment]
Finally I had some time to try to connect the Paradox board with the ESPHome running on a Wemo D1 Mini.
Unfortunately it didn't work (I must have been doing something wrong).

Could you please help me figure it out what is wrong with my setup?

I have the paradox_combus_esphome.h unchanged:
```
#include "esphome.h"

#define CLK 5 // Keybus Yellow
#define DTA 4 // Keybus Green
```
I presume these mean the clock (yellow) signal should be on the Wemo's D5 pin, while the data (green) on the Wemo's D4.

My alarm.yaml has:
```
status_led:
  pin:
    number: D4
    inverted: yes
```
Does this have anything related to the connection setup?

The ESPhome logs the pings (every 30secs?) and also shows the intialized alarm sensors as off. The connection is ON however the status of the alarm is empty and the alarm e.g. motion sensor status change cannot be seen on the ESPHome's webUI.

What am I doing wrong?

**Comment by Damian-Mora** [comment]
> Finalmente tuve algo de tiempo para intentar conectar la placa Paradox con el ESPHome ejecutándose en un Wemo D1 Mini. Desafortunadamente no funcionó (debo haber estado haciendo algo mal).
> 
> ¿Podría por favor ayudarme a averiguar qué está mal con mi configuración?
> 
> Tengo el paradox_combus_esphome.h sin cambios:
> 
> ```
> #include "esphome.h"
> 
> #define CLK 5 // Keybus Yellow
> #define DTA 4 // Keybus Green
> ```
> 
> Supongo que esto significa que la señal del reloj (amarillo) debe estar en el pin D5 de Wemo, mientras que los datos (verde) en el D4 de Wemo.
> 
> Mi alarm.yaml tiene:
> 
> ```
> status_led:
>   pin:
>     number: D4
>     inverted: yes
> ```
> 
> ¿Tiene esto algo relacionado con la configuración de la conexión?
> 
> El ESPhome registra los pings (¿cada 30 segundos?) y también muestra los sensores de alarma inicializados como apagados. La conexión está ENCENDIDA, sin embargo, el estado de la alarma está vacío y la alarma, por ejemplo, el cambio de estado del sensor de movimiento, no se puede ver en la interfaz de usuario web de ESPHome.
> 
> ¿Qué estoy haciendo mal?

El negativo del panel debe ir conectado al negativo del esp. Este debe ir conectado Así lo estés alimentado desde el USB

**Comment by amaximus** [comment]
Muchas gracias @Damian-Mora .
Unfortunately it didn't work.
I might need some simple clarification on:
* the `define CLK 5` in paradox_combus_esphome.h refers to GPIO5 or D5 on Wemo D1 mini? Simlarly DTA 4 refers to GPIO4 or D4? ESPHome site [2] says pins are GPIO numbers.
* how does `number: D4` in alarm.yaml relate to these above (DTA?)?

[2] https://esphome.io/guides/configuration-types.html#pin
